networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - server
      - client
    networks:
      - dev

  server:
    build:
      context: ./lovely-pets-server
    networks:
      - dev


  client:
    build:
      context: ./lovely-pets-client
    networks:
      - dev